export const ARTICLES = {
  CHECK_STATE_CHANGE: 'CHECK_STATE_CHANGE',
  DELETE_ARTICLE_STATE: 'DELETE_ARTICLE_STATE',
  ETAG_CHANGE: 'ETAG_CHANGE',
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FETCH_SINGLE_ARTICLE: 'FETCH_SINGLE_ARTICLE',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FILTER_OPTION_CHANGE: 'FILTER_OPTION_CHANGE',
  GROUP_OPERATION_CHANGE: 'GROUP_OPERATION_CHANGE',
  MOVE_CATEGORY_STATE: 'MOVE_CATEGORY_STATE',
}

export const CATEGORIES = {
  ADD_CATEGORY_CANCEL: 'ADD_CATEGORY_CANCEL',
  ADD_CATEGORY_CONFIRM: 'ADD_CATEGORY_CONFIRM',
  ADD_CATEGORY_VALUE_CHANGE: 'ADD_CATEGORY_VALUE_CHANGE',
  ADD_CATEGORY_DIV_STATE_CHANGE: 'ADD_CATEGORY_DIV_STATE_CHANGE',
  CATEGORY_ORDER_CHANGE: 'CATEGORY_ORDER_CHANGE',
  DELETE_CATEGORY_CANCEL: 'DELETE_CATEGORY_CANCEL',
  DELETE_CATEGORY_CONFIRM: 'DELETE_CATEGORY_CONFIRM',
  DELETE_CATEGORY_HANDLE: 'DELETE_CATEGORY_HANDLE',
  DELETE_CATEGORY_STATE: 'DELETE_CATEGORY_STATE',
  FETCH_CATEGORY_DATA: 'FETCH_CATEGORY_DATA',
  UPDATE_CATEGORY_ORDER: 'UPDATE_CATEGORY_ORDER'
}

export const CATEGORY_REFACT = {
  ARTICLE_ORDER_CHANGE: 'ARTICLE_ORDER_CHANGE',
  CATEGORY_EXPAND_CHANGE: 'CATEGORY_EXPAND_CHANGE',
  CATEGORY_PREFACE_CHANGE: 'CATEGORY_PREFACE_CHANGE',
  GET_CATEGORY_TREE: 'GET_CATEGORY_TREE',
  GET_REFACT_DETAIL: 'GET_REFACT_DETAIL'
}

export const LABELS = {
  FETCH_LABEL_DATA: 'FETCH_LABEL_DATA'
}
 
export const PHOTOS = {
  FETCH_GROUP_PHOTOS: 'FETCH_GROUP_PHOTOS',
  FETCH_PHOTO_GROUPS: 'FETCH_PHOTO_GROUPS',
  FETCH_SINGLE_PHOTO: 'FETCH_SINGLE_PHOTO',
  GROUP_ADD_CANCEL: 'GROUP_ADD_CANCEL',
  GROUP_ADD_CONFIRM: 'GROUP_ADD_CONFIRM',
  GROUP_OPE_IMG_STATE_TOGGLE: 'GROUP_OPE_IMG_STATE_TOGGLE',
  GROUP_SHOW_ADD_DIALOG: 'GROUP_SHOW_ADD_DIALOG',
  GROUP_ITEM_HIDE_DELETE: 'GROUP_ITEM_HIDE_DELETE',
  GROUP_ITEM_SHOW_DELETE: 'GROUP_ITEM_SHOW_DELETE',
  GROUP_ITEM_HIDE_INPUT: 'GROUP_ITEM_HIDE_INPUT',
  GROUP_ITEM_SHOW_INPUT: 'GROUP_ITEM_SHOW_INPUT',
  GROUP_ITEM_DELETE_STATE: 'GROUP_ITEM_DELETE_STATE',
  GROUP_ITEM_INPUT_STATE: 'GROUP_ITEM_INPUT_STATE',
  GROUP_ITEM_CLICK: 'GROUP_ITEM_CLICK',
  GROUP_ITEM_DELETE: 'GROUP_ITEM_DELETE',
  GROUP_ITEM_RENAME: 'GROUP_ITEM_RENAME',
  PFOB_DELETE_DIALOG_VISIBLE: 'PFOB_DELETE_DIALOG_VISIBLE',
  PFOB_MOVE_DIALOG_VISIBLE: 'PFOB_MOVE_DIALOG_VISIBLE',
  PHOTO_CHECK_STATE_CHANGE: 'PHOTO_CHECK_STATE_CHANGE',
  PHOTO_CHECK_STATE_CHANGE_ALL: 'PHOTO_CHECK_STATE_CHANGE_ALL',
  PHOTO_DELETE_BY_GROUP: 'PHOTO_DELETE_BY_GROUP',
  PHOTO_DELETE_DIALOG_VISIBLE: 'PHOTO_DELETE_DIALOG_VISIBLE',
  PHOTO_DELETE_SINGLE: 'PHOTO_DELETE_SINGLE',
  PHOTO_GROUP_CHANGE: 'PHOTO_GROUP_CHANGE',
  PHOTO_INPUT_DIALOG_VISIBLE: 'PHOTO_INPUT_DIALOG_VISIBLE',
  PHOTO_MOVE_BY_GROUP: 'PHOTO_MOVE_BY_GROUP',
  PHOTO_MOVE_DIALOG_VISIBLE: 'PHOTO_MOVE_DIALOG_VISIBLE',
  PHOTO_MOVE_GROUP: 'PHOTO_MOVE_GROUP',
  PHOTO_MOVE_GROUP_SINGLE: 'PHOTO_MOVE_GROUP_SINGLE',
  PHOTO_RENAME: 'PHOTO_RENAME',
  PHOTO_UPLOAD: 'PHOTO_UPLOAD',
  REFETCH: 'REFETCH'
}
