host: localhost
user: root
pass: root
dbname: blog_node
charset: utf8mb4
collate: utf8mb4_unicode_ci
tables:
  - articles:
      rows:
        - id:
            type: int(11)
            'null': false
            auto_increment: true
        - title:
            type: char(50)
            'null': false
        - content:
            type: text
        - descp:
            type: varchar(500)
        - category:
            type: int(11)
            'null': false
        - label:
            type: char(100)
        - state:
            type: 'enum(''on'',''off'')'
            default: 'off'
        - top:
            type: tinyint(4)
            default: '0'
        - addtime:
            type: int(11)
            'null': false
        - modtime:
            type: int(11)
            'null': false
            default: '0'
        - pageview:
            type: int(11)
            default: '0'
        - suborder:
            type: int(11)
            default: '0'
      keys:
        primary:
          - id
        unique:
          - title
        foreign: []
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
  - categories:
      rows:
        - id:
            type: int(11)
            'null': false
            auto_increment: true
        - name:
            type: char(20)
            'null': false
        - parent:
            type: int(11)
            'null': false
        - addtime:
            type: int(11)
            'null': false
        - descp:
            type: char(50)
            'null': false
        - articlecnt:
            type: int(11)
            default: '0'
        - preface:
            type: int(11)
            default: '0'
        - mainorder:
            type: int(11)
            default: '0'
            comment: '在列表中的顺序'
        - suborder:
            type: int(11)
            default: '0'
            comment: "在列表树中的顺序"
      keys:
        primary:
          - id
        unique:
          - name
        foreign: []
      charset: utf8
  - labels:
      rows:
        - id:
            type: int(11)
            'null': false
            auto_increment: true
        - name:
            type: char(10)
            'null': false
        - articles:
            type: int(11)
            default: '0'
        - hotmark:
            type: int(11)
            default: '0'
        - addtime:
            type: int(11)
            'null': false
      keys:
        primary:
          - id
        unique:
          - name
        foreign: []
      charset: utf8
  - photogroups:
      rows:
        - id:
            type: int(11)
            'null': false
            auto_increment: true
        - name:
            type: char(10)
            'null': false
        - count:
            type: int(11)
            default: '0'
        - addtime:
            type: int(11)
            'null': false
      keys:
        primary:
          - id
        unique:
          - name
        foreign: []
      charset: utf8
  - photos:
      rows:
        - id:
            type: int(11)
            'null': false
            auto_increment: true
        - name:
            type: varchar(50)
            'null': false
        - title:
            type: varchar(50)
            'null': false
        - photogroup:
            type: int(11)
            'null': false
            default: '1'
        - label:
            type: varchar(100)
        - addtime:
            type: int(11)
            'null': false
      keys:
        primary:
          - id
        unique:
          - name
        foreign: []
      charset: utf8
  - uservisit:
      rows:
        - usercookie:
            type: char(32)
            'null': false
        - ip:
            type: char(32)
            'null': false
        - time:
            type: int(11)
            'null': false
      keys:
        foreign: []
      charset: utf8
  - visithistory:
      rows:
        - date:
            type: int(11)
            'null': false
        - pv:
            type: int(11)
            default: '0'
        - uv:
            type: int(11)
            default: '0'
        - ip:
            type: int(11)
            default: '0'
      keys:
        primary:
          - date
        foreign: []
      charset: utf8
